import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Results from "@/components/Results";
import requests from "@/utils/requests"; // Đảm bảo bạn import `requests` từ utils

export default function Home({ results }) { // Nhận props `results` từ `getServerSideProps`
	console.log(results)
	return (
		<div>
			<Head>
				<title>Create Next App hulu 2.0</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* Header */}
			<Header />
			{/* Nav */}
			<Nav />
			{/* Results */}
			<Results results={results} /> {/* Truyền `results` vào `Results` */}
		</div>
	);
}

export async function getServerSideProps(context) {
	const genre = context.query.genre;
	const request = await fetch(
		`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
	).then((res) => res.json());

	return {
		props: {
			results: request.results,
		},
	};
}
